version: '3'
services:
  rockylinux:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tauruspet-mirror
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
    volumes:
      - ./:/home/pydev/mr_transfer
