FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3 \
    python3-venv \
    python3-distutils \
    python3-pip \
    build-essential \
    gcc \
    make \
    binutils \
    patchelf \
    git \
    vim \
    rsync \
    curl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /code

# Create dir where data is stored on actual pet server
RUN mkdir -p /data8/data/

CMD ["/bin/bash"]
